### ISSUE TITLE
Shopware 5.2.0 RC3 / Build Rev 201606290954

### ISSUE THREAD

**Issue by skperformance** [shopwareLabs/SwagVariantFilter#3]
Backend says, that no license is available vor swag variant filter. what can i do?

**Comment by mitelg** [comment]
hi @skperformance ,
this plugins needs no license. I have just installed the plugin on the current Shopware 5.2 without problems. Maybe another plugin causes this error

**Comment by skperformance** [comment]
no, in the License-Manager stay following text: "not licensed". Not from another Plugin.

Beste Grüße aus Stralsund
Best regards from Stralsund / Germany.

Sebastian Krüger
Geschäftsleitung / CEO
Felgenonkel.de

Facebook: www.facebook.com/felgenonkel/https://www.facebook.com/felgenonkel/
Webshop: www.felgenonkel.de/http://felgenonkel.de/
Bewertungen: www.facebook.com/felgenonkel/reviews/http://www.facebook.com/felgenonkel/reviews/

---

Von: Michael Telgmann notifications@github.com
Gesendet: Montag, 4. Juli 2016 09:27
An: shopwareLabs/SwagVariantFilter
Cc: skperformance; Mention
Betreff: Re: [shopwareLabs/SwagVariantFilter] Shopware 5.2.0 RC3 / Build Rev 201606290954 (#3)

hi @skperformancehttps://github.com/skperformance ,
this plugins needs no license. I have just installed the plugin on the current Shopware 5.2 without problems. Maybe another plugin causes this error

##

**Comment by fixing-it** [comment]
same here:

> Möglicherweise sind Sie Opfer einer Produktfälschung geworden. Account aufrufen
> 
> Für die folgenden Plugins liegt keine gültige Lizenz vor:
> Varianten Filter

It shows up when entering the backend.

**Comment by mitelg** [comment]
Hi,
I created a ticket for our guys of the internal systems. We will inform you, as soon, we have more information

**Comment by mitelg** [comment]
Hi @skperformance @fixing-it 
do you still have Problems with the license? otherwise I will close this issue
