### ISSUE TITLE
Bug when used on PHP7

### ISSUE THREAD

**Issue by sahat81** [shopwareLabs/SwagVariantFilter#7]
I receive this error message when switching our server to PHP7

PHP Fatal error: 
Uncaught TypeError: Argument 1 passed to Shopware_Plugins_Frontend_SwagVariantFilter_Bootstrap::onStartDispatch() must be an instance of Enlight_Controller_EventArgs, instance of Enlight_Controller_ActionEventArgs given, called in .../engine/Library/Enlight/Event/Handler/Plugin.php on line 149 and defined in .../engine/Shopware/Plugins/Community/Frontend/SwagVariantFilter/Bootstrap.php:46

**Comment by sahat81** [comment]
Hi @ngoedde  / @dnoegel  / @mitelg 

I fixed this for our shop by simply changing:
Enlight_Controller_EventArgs to Enlight_Controller_ActionEventArgs

in the specified line of the error message (46):
`public function onStartDispatch(Enlight_Controller_EventArgs $args)`

We still haven't publish this fix to live shop since I'm not sure if it really is that simple.
Can anyone please confirm it? Unfortunately I don't have any right to push this update,
so would be great if anyone can help.

Thanks! (^^)

**Comment by dnoegel** [comment]
Hi,

looks good. You can just fork this project and then create a pull request.

Thanks in advance,

Daniel

**Comment by sahat81** [comment]
Hi Daniel, thanks for the feedback :) I just did, cheers!

Sahat
